apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bae-activation-service.fullname" . }}
  labels:
    {{ include "bae-activation-service.labels" . | nindent 4 }}
type: Opaque
data:
  baeKeyrockPassword: {{ .Values.baeKeyrock.password | b64enc }}
  providerKeyrockPassword: {{ .Values.providerKeyrock.password | b64enc }}
  providerUmbrellaAdminToken: {{ .Values.providerUmbrella.admin_token | b64enc }}
  providerUmbrellaApiKey: {{ .Values.providerUmbrella.api_key | b64enc }}
  
