{{- if .Values.bizEcosystemChargingBackend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizEcosystemChargingBackend.fullname" . }}
  labels:
    {{ include "bizEcosystemChargingBackend.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.bizEcosystemChargingBackend.db.password | b64enc }}
  {{- if .Values.bizEcosystemChargingBackend.email.smtp }}
  {{- if .Values.bizEcosystemChargingBackend.email.smtp.password }}
  smtpPassword: {{ .Values.bizEcosystemChargingBackend.email.smtp.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.bizEcosystemChargingBackend.paypal }}
  {{- if .Values.bizEcosystemChargingBackend.paypal.clientSecret }}
  paypalClientSecret: {{ .Values.bizEcosystemChargingBackend.paypal.clientSecret | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

