apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mintaka.fullname" . }}
  labels:
    {{ include "mintaka.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.db.password | b64enc }}