{{- if .Values.bizEcosystemLogicProxy.theme.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "bizEcosystemLogicProxy.fullname" . }}-themes
  {{- with .Values.bizEcosystemLogicProxy.theme.annotations  }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "bizEcosystemLogicProxy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bizEcosystemLogicProxy.theme.size | quote }}
{{- end }}
