{{- if .Values.bizEcosystemLogicProxy.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizEcosystemLogicProxy.fullname" . }}
  labels:
    {{ include "bizEcosystemLogicProxy.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.bizEcosystemLogicProxy.db.password | b64enc }}
  oauthClientSecret: {{ .Values.oauth.clientSecret | b64enc }}
{{- end }}
