# Default values for bae-activation-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## -- option to override the name config in the _helpers.tpl for the whole chart
nameOverride: ""
## -- option to override the fullname config in the _helpers.tpl for the whole chart
fullnameOverride: ""

## configuration for the k8s service to access the activation service
service:
  # -- service type
  type: ClusterIP
  # -- port to be used by the service
  port: 80
  # -- addtional annotations, if required
  annotations: {}

# -- if a specific service account should be used, it can be configured here
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- specifies if the account should be created
  create: false

## deployment specific configuration
deployment:
  # -- initial number of target replications, can be different if autoscaling is enabled
  replicaCount: 1
  # -- number of old replicas to be retained
  revisionHistoryLimit: 3
  ## configuration of the update strategy
  updateStrategy:
    # -- type of the update
    type: RollingUpdate
    # -- new pods will be added gradually
    rollingUpdate:
      # -- number of pods that can be created above the desired amount while updating
      maxSurge: 1
      # -- number of pods that can be unavailable while updating
      maxUnavailable: 0
  ## configuration of the image to be used
  image:
    # -- image name
    # ref: https://hub.docker.com/r/fiware/bae-activation-service
    repository: fiware/bae-activation-service
    # -- tag of the image to be used
    tag: v0.0.3
    # -- specification of the image pull policy
    pullPolicy: IfNotPresent
  # -- additional labels for the deployment, if required
  additionalLabels: {}
  # -- additional annotations for the deployment, if required
  additionalAnnotations: {}
  ## Activation Service resource requests and limits, we leave the default empty to make that a concious choice by the user.
  ## for the autoscaling to make sense, you should configure this.
  # resources:
    # limits:
      # cpu: 100m
      # memory: 128Mi
    # requests:
      # cpu: 100m
      # memory: 128Mi
  # -- selector template
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
  # -- tolerations template
  # ref: ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
  # -- affinity template
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  ## liveness and readiness probes of the activation service, they will be evaluated against the version endpoint
  # ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 21
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30

## pod autoscaling configuration, use for automatic scaling of the pods
autoscaling:
  #  -- should autoscaling be enabled for the activation service
  enabled: false
  # -- minimum number of running pods
  minReplicas: 1
  # -- maximum number of running pods
  maxReplicas: 10
  # -- metrics to react on
  metrics: []

## openshift specific route definition. Will not work on plain k8s
route:
  ## -- should the deployment create openshift routes
  enabled: false
  # -- annotations to be added to the route
  annotations: {}
  # -- host to be used
  # host: localhost
  # -- tls configuration for the route
  tls: {}
  # termination: edge

## ingress configuration
ingress:
  # -- should there be an ingress to connect the activation service with the public internet
  enabled: false
  # -- annotations to be added to the ingress
  annotations: {}
    # kubernetes.io/ingress.class: "ambassador"
    ## example annotations, allowing cert-manager to automatically create tls-certs and forcing everything to use ssl.
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"
  # -- all hosts to be provided
  hosts: []
    ## provide a hosts and the paths that should be available
    # - host: localhost
      # paths:
      # - /
  # -- configure the ingress' tls
  tls: []
    # - secretName: bae-as-tls
      # hosts:
        # - bae-activation-service.fiware.org
        
## Configuration of Marketplace Keyrock instance
baeKeyrock:
  ## Server URL
  server: https://keyrock.marketplace.org
  ## Application/Client-ID within Marketplace Keyrock
  appid: bae-provider-app-id
  ## Username in Marketplace Keyrock
  username: my_user
  ## Password in Marketplace Keyrock
  password: my_pw

## Configuration of data service provider Keyrock instance
providerKeyrock:
  ## Server URL
  server: https://keyrock.provider.org
  ## Application/Client-ID within Provider Keyrock
  appid: provider-app-id
  ## Username in Provider Keyrock
  username: my_user
  ## Password in Provider Keyrock
  password: my_pw

## Configuration of data service provider API Umbrella instance
providerUmbrella:
  ## Server URL
  server: https://umbrella.provider.org
  ## Admin Token of API Umbrella Admin Account
  admin_token: my-admin-token
  ## API Key of API User
  api_key: my-api-key

# -- a list of additional env vars to be set
# ref: https://github.com/FIWARE-AI-Marketplace/bae-activation-service
additonalEnvVars: []
