{{- if .Values.iota.authentication -}}
{{- if eq .Values.iota.authentication.identityManager.type "keystone" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iota-ul.fullname" . }}
  labels:
    {{ include "iota-ul.labels" . | nindent 4 }}
type: Opaque
data:
  iotaUser: {{ .Values.iota.authentication.identityManager.keystone.user | b64enc }}
  iotaPassword: {{ .Values.iota.authentication.identityManager.keystone.password | b64enc }}
{{- end }}
{{- end }}