{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iota-ul.fullname" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "iota-ul.labels" . | nindent 4 }}
{{- end }}