name: Chart Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  # lint the charts
  lint:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: ./lint.sh

  eval:

    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - uses: actions/checkout@v2

      - name: Eval
        run: |
          .github/build/install.sh
          ./eval.sh

  install-chart:
    runs-on: ubuntu-latest
    needs:
      - lint
      - eval
    strategy:
      matrix:
        k8s:
          - v1.16.15
          - v1.17.11
          - v1.18.6
          - v1.19.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@master
        with:
          config: .github/build/kind-config.yaml
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/ct.yaml